# Generated by Django 4.2 on 2023-05-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200, null=True)),
                ('productType', models.CharField(max_length=200, null=True)),
                ('cost', models.FloatField(null=True)),
                ('color', models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Dark Green', 'Dark Green'), ('Galaxy', 'Galaxy'), ('Gray', 'Gray'), ('Green', 'Green'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Rifle Green', 'Rifle Green'), ('Yellow', 'Yellow'), ('White', 'White')], max_length=200, null=True)),
                ('size', models.CharField(choices=[('Baby', 'Baby'), ('Mini', 'Mini'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], max_length=200, null=True)),
                ('quanity', models.FloatField(null=True)),
            ],
        ),
    ]
