# Generated by Django 4.2 on 2023-05-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='product_Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productType',
            new_name='product_Type',
        ),
    ]
