# Generated by Django 4.2 on 2023-05-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quanity',
            field=models.IntegerField(null=True),
        ),
    ]
