# Generated by Django 4.2 on 2023-05-07 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_product_product_id_alter_product_quanity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_ID',
        ),
    ]
